name: Waka Readme

on:
  schedule:
    - cron: '0 */5 * * *'  # every hour (change to '0 0 * * *' for daily)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SYMBOL_VERSION: '2'
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_DAYS_OF_WEEK : "False"
          SHOW_OS : "True"
          SHOW_PROJECTS : "True"
          SHOW_LANGUAGE_PER_REPO : "True"
          SHOW_SHORT_INFO : "False"
          SHOW_LOC_CHART : "False"
